
% Monte Carlo test for Buffon's needle
clc;clear;figure(1);clf;

% D is each line distance
D = 5 ;

% d is line length
d = 10 ;

% L is each needle's length
L = 1 ;

% n is line number
n = 5 ;

% N is the time to run 
N = 500 ;

% a is the number fit for require

val = 1;
     
hpop = uicontrol('style','popup',...
    'string','Rand|Betarnd|Binornd|Chi2rnd|Exprnd|Frnd|Gamrnd|Geornd|Hygernd|Lognrnd|Nbinrnd|Ncfrnd|Nctrnd|Ncx2rnd|Normrnd|Poissrnd|Raylrnd|Trnd|Unidrnd|Unifrnd|Weibrnd',...
    'position',[20 320 100 50],...
    'callback','setmap');

button1 = uicontrol('style','pushbutton',...
    'string','ok',...
    'position',[20 150 100 70],...
    'callback',[...
'a = 0 ;',...
'tic;',...
'for i = 1:N;',...
'[x y th] = rrr(val,d,n,D);',...
   'yy = y + L * sin(th) ;',...
   'p1 = mod(y,D) ;',...
   'p2 = mod(yy,D) ;',...
 '  if abs(p1-p2) > D - L',...
'       a = a + 1 ;',...
'   end ;',...
'end;',...
'toc;',...
'a/N'...
]);



